// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtzsgxpjrrjnmwtqmnah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0enNneHBqcnJqbm13dHFtbmFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNTYwMjMsImV4cCI6MjA2NTkzMjAyM30.7uJ_zqiWUaJxLD5o_bZ4NYXARzFIRp1wIqQ_vFrFB6M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);