// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rdfepdnffqpfqbyfkqyu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkZmVwZG5mZnFwZnFieWZrcXl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODk4OTYsImV4cCI6MjA2NTU2NTg5Nn0.L3a5XCkjDelUpuNSCzBPWfRvDbkv99EUQY6iLs3YvuM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);