name: Database Backup
on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours at minute 0
  workflow_dispatch:     # Manual trigger

permissions:
  contents: write

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PostgreSQL Client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
        
      - name: Create backup directory
        run: |
          TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
          BACKUP_DIR="backups/$TIMESTAMP"
          mkdir -p "$BACKUP_DIR"
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV
          echo "BACKUP_DIR=$BACKUP_DIR" >> $GITHUB_ENV
          
      - name: Export Database Backup
        env:
          PGPASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
        run: |
          # Backup all data
          pg_dump -h aws-0-us-east-2.pooler.supabase.com \
                  -U postgres.vtzsgxpjrrjnmwtqmnah \
                  -d postgres \
                  -p 6543 \
                  --data-only \
                  --schema=public \
                  --no-owner \
                  --no-privileges > "$BACKUP_DIR/folyx_data.sql"
          
          # Backup complete schema (structure + data)
          pg_dump -h aws-0-us-east-2.pooler.supabase.com \
                  -U postgres.vtzsgxpjrrjnmwtqmnah \
                  -d postgres \
                  -p 6543 \
                  --schema=public \
                  --no-owner \
                  --no-privileges > "$BACKUP_DIR/folyx_complete.sql"
          
      - name: Create backup info
        run: |
          echo "Folyx Database Backup - $(date)" > "$BACKUP_DIR/backup_info.txt"
          echo "Backup Directory: $BACKUP_DIR" >> "$BACKUP_DIR/backup_info.txt"
          echo "" >> "$BACKUP_DIR/backup_info.txt"
          echo "Files created:" >> "$BACKUP_DIR/backup_info.txt"
          echo "- folyx_data.sql (data only)" >> "$BACKUP_DIR/backup_info.txt"
          echo "- folyx_complete.sql (schema + data)" >> "$BACKUP_DIR/backup_info.txt"
          echo "" >> "$BACKUP_DIR/backup_info.txt"
          echo "File sizes:" >> "$BACKUP_DIR/backup_info.txt"
          echo "Data: $(du -h $BACKUP_DIR/folyx_data.sql | cut -f1)" >> "$BACKUP_DIR/backup_info.txt"
          echo "Complete: $(du -h $BACKUP_DIR/folyx_complete.sql | cut -f1)" >> "$BACKUP_DIR/backup_info.txt"
          echo "" >> "$BACKUP_DIR/backup_info.txt"
          echo "Restore commands:" >> "$BACKUP_DIR/backup_info.txt"
          echo "Data only: psql -h host -U user -d db -f folyx_data.sql" >> "$BACKUP_DIR/backup_info.txt"
          echo "Complete: psql -h host -U user -d db -f folyx_complete.sql" >> "$BACKUP_DIR/backup_info.txt"
          
      - name: Commit backups
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add backups/
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Hourly database backup $(date +"%Y-%m-%d %H:%M")"
            git push
          else
            echo "No changes to commit"
          fi